project/models.py
# project/models.py


import datetime

from project import db, bcrypt


class User(db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String, unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)
    registered_on = db.Column(db.DateTime, nullable=False)
    admin = db.Column(db.Boolean, nullable=False, default=False)
    confirmed = db.Column(db.Boolean, nullable=False, default=False)
    confirmed_on = db.Column(db.DateTime, nullable=True)

    def __init__(self, email, password, confirmed, paid=False, admin=False, confirmed_on=None):
        self.email = email
        self.password = bcrypt.generate_password_hash(password)
        self.registered_on = datetime.datetime.now()
        self.admin = admin
        self.confirmed = confirmed
        self.confirmed_on = confirmed_on

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id

    def __repr__(self):
        return '<email {}'.format(self.email)

class Petition(db.Model):

    __tablename__ = "petitions"

    publicKey = db.Column(db.String)
    masterAccount = db.Column(db.String, nullable=False)
    name = db.Column(db.String, nullable=False)
    uid = db.Column(db.Integer, primary_key=True)
    yesCount = db.Column(db.Integer)
    startDate = db.Column(db.Date, nullable=True)
    endDate = db.Column(db.Date, nullable=True)

    def __init__(self, name, publicKey, masterAccount, yesCount, startDate=None, endDate=None):
        self.name = name
        self.publicKey = publicKey
        self.masterAccount = masterAccount
        self.yesCount = yesCount
        self.startDate = startDate
        self.endDate = endDate


class Feedback(db.Model):

    __tablename__ = "feedback"

    fid = db.Column(db.Integer, primary_key=True)
    q1 = db.Column(db.String, nullable=True)
    q2 = db.Column(db.String, nullable=True)
    q3 = db.Column(db.String, nullable=True)
    q4 = db.Column(db.String, nullable=True)
    q5 = db.Column(db.String, nullable=True)

    def __init__(self, q1, q2, q3, q4, q5):
        self.q1 = q1
        self.q2 = q2
        self.q3 = q3
        self.q4 = q4
        self.q5 = q5

project/feedback/forms.py
# project/feedback/forms.py


from flask_wtf import Form
from wtforms import TextField
from wtforms.validators import DataRequired, Email, Length, EqualTo

from project.models import User


class FeedbackForm(Form):
    q1 = TextField('q1')
    q2 = TextField('q2')
    q3 = TextField('q3')
    q4 = TextField('q4')
    q5 = TextField('q5')

project/petition/forms.py
# project/user/forms.py


from flask_wtf import Form
from wtforms import TextField, PasswordField, DateField
from wtforms.validators import DataRequired, Email, Length, EqualTo

from project.models import User


class LoginForm(Form):
    email = TextField('email', validators=[DataRequired(), Email()])
    password = PasswordField('password', validators=[DataRequired()])

class RegisterForm(Form):
    email = TextField(
        'email',
        validators=[DataRequired(), Email(message=None), Length(min=6, max=40)])
    password = PasswordField(
        'password',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Repeat password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        return True

class CreatePetitionForm(Form):
    name = TextField('name', validators=[DataRequired()])
    startDate = DateField('startDate', format="%m/%d/%Y")
    endDate = DateField('endDate', format="%m/%d/%Y")

class ListPetitionForm(Form):
    foo = "foo"

class ChangePasswordForm(Form):
    password = PasswordField(
        'password',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Repeat password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )

project/user/forms.py
# project/user/forms.py


from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, Email, Length, EqualTo

from project.models import User


class LoginForm(Form):
    email = TextField('email', validators=[DataRequired(), Email()])
    password = PasswordField('password', validators=[DataRequired()])

class RegisterForm(Form):
    email = TextField(
        'email',
        validators=[DataRequired(), Email(message=None), Length(min=6, max=40)])
    password = PasswordField(
        'password',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Repeat password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        return True

class CreatePetitionForm(Form):
    name = TextField('name', validators=[DataRequired()])


class ChangePasswordForm(Form):
    password = PasswordField(
        'password',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Repeat password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )

project/__init__.py
# project/__init__.py


#################
#### imports ####
#################

import os

from flask import Flask, render_template
from flask.ext.login import LoginManager
from flask.ext.bcrypt import Bcrypt
from flask_mail import Mail
from flask.ext.debugtoolbar import DebugToolbarExtension
from flask.ext.sqlalchemy import SQLAlchemy


################
#### config ####
################

app = Flask(__name__)

app.config.from_object("project.config.DevelopmentConfig")

####################
#### extensions ####
####################

login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
mail = Mail(app)
toolbar = DebugToolbarExtension(app)
db = SQLAlchemy(app)


####################
#### blueprints ####
####################

from project.main.views import main_blueprint
from project.user.views import user_blueprint
from project.petition.views import petition_blueprint
from project.feedback.views import feedback_blueprint
app.register_blueprint(main_blueprint)
app.register_blueprint(user_blueprint)
app.register_blueprint(petition_blueprint)
app.register_blueprint(feedback_blueprint)


####################
#### flask-login ####
####################

from project.models import User

login_manager.login_view = "user.login"
login_manager.login_message_category = "danger"


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


########################
#### error handlers ####
########################

@app.errorhandler(403)
def forbidden_page(error):
    return render_template("errors/403.html"), 403


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

project/feedback/views.py
# project/feedback/views.py

from .forms import FeedbackForm
from project.token import generate_confirmation_token, confirm_token
from project.decorators import check_confirmed
from project.models import User, Petition, Feedback
from project.email import send_email
from project import db


from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask.ext.login import login_user, logout_user, \
    login_required, current_user



user_blueprint      = Blueprint('user', __name__,)
petition_blueprint  = Blueprint('petition', __name__,)
feedback_blueprint  = Blueprint('feedback', __name__,)

##################################################
#                                                #
# Return type:                                   #
# (render_template)                              #
#                                                #
# Parameters:                                    #
# None                                           #
#                                                #
#                                                #
##################################################
@feedback_blueprint.route('/feedback', methods=['GET', 'POST'])
@login_required
@check_confirmed
def giveFeedback():
    form = FeedbackForm(request.form)
    if form.validate_on_submit():
        feedback = Feedback(
            q1=form.q1.data,
            q2=form.q2.data,
            q3=form.q3.data,
            q4=form.q4.data,
            q5=form.q5.data
        )
        db.session.add(feedback)
        db.session.commit()
        flash('Feedback has been created!.', 'success')

    return render_template('feedback/feedback.html', form=form)

project/main/views.py
# project/main/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint
from flask.ext.login import login_required


################
#### config ####
################

main_blueprint = Blueprint('main', __name__,)


################
#### routes ####
################

@main_blueprint.route('/')
def home():
    return render_template('main/index.html')

project/user/views.py
# project/user/views.py


#################
#### imports ####
#################
from algosdk import encoding
from algosdk import transaction
from algosdk import kmd
from algosdk import algod
from algosdk import account
from algosdk import mnemonic
import json
import hashlib


from project.email import send_email
from project.decorators import check_confirmed
from project.token import generate_confirmation_token, confirm_token

from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask.ext.login import login_user, logout_user, \
    login_required, current_user

from project.models import User
# from project.email import send_email
from project import db, bcrypt
from .forms import LoginForm, RegisterForm, ChangePasswordForm, CreatePetitionForm

import datetime

################
#### config ####
################

user_blueprint = Blueprint('user', __name__,)


################
#### routes ####
################

@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)

    if form.validate_on_submit():
        if "@bcmail.cuny.edu" in str(form.email.data) or "@bcacad.local " in str(form.email.data):
            encryptedEmail = str(hashlib.sha256(str(form.email.data).encode()).hexdigest())
            user = User(
                email=encryptedEmail,
                password=form.password.data,
                confirmed=False
            )
            db.session.add(user)
            db.session.commit()

            token = generate_confirmation_token(user.email)
            confirm_url = url_for('user.confirm_email', token=token, _external=True)
            html = render_template('user/activate.html', confirm_url=confirm_url)
            subject = "Please confirm your email"
            send_email(form.email.data, subject, html)

            login_user(user)

            flash('A confirmation email has been sent via email.', 'success')
            return redirect(url_for("user.unconfirmed"))
        else:
            flash('Error: Must have a Brooklyn College email address.', 'warning')

    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        encryptedEmail = str(hashlib.sha256(str(form.email.data).encode()).hexdigest())
        user = User.query.filter_by(email=encryptedEmail).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('Welcome.', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', form=form)

@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out.', 'success')
    return redirect(url_for('user.login'))


@user_blueprint.route('/confirm/<token>')
@login_required
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
    user = User.query.filter_by(email=email).first_or_404()
    if user.confirmed:
        flash('Account already confirmed. Please login.', 'success')
    else:
        user.confirmed = True
        user.confirmed_on = datetime.datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'success')

        #################################################################################
        ## This wold be a good place to implement the user's blockchain creds initiation.
        ##
        ## Required functions from Algorand SDK.
        ## handle = kcl.init_wallet_handle(wallet_id, wallet_pswd)
        ## private_key_1, address_1 = account.generate_account()
        ##
        ##
        #################################################################################

    return redirect(url_for('main.home'))

@user_blueprint.route('/resend')
@login_required
def resend_confirmation():
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('user.confirm_email', token=token, _external=True)
    html = render_template('user/activate.html', confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_email(current_user.email, subject, html)
    flash('A new confirmation email has been sent.', 'success')
    return redirect(url_for('user.unconfirmed'))

@user_blueprint.route('/unconfirmed')
@login_required
def unconfirmed():
    if current_user.confirmed:
        return redirect('main.home')
    flash('Please confirm your account!', 'warning')
    return render_template('user/unconfirmed.html')

@user_blueprint.route('/profile', methods=['GET', 'POST'])
@login_required
@check_confirmed
def profile():
    form = ChangePasswordForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=current_user.email).first()
        if user:
            user.password = bcrypt.generate_password_hash(form.password.data)
            db.session.commit()
            flash('Password successfully changed.', 'success')
            return redirect(url_for('user.profile'))
        else:
            flash('Password change was unsuccessful.', 'danger')
            return redirect(url_for('user.profile'))
    return render_template('user/profile.html', form=form)

project/templates/user/activate.html
<p>Welcome! Thanks for signing up. Please follow this link to activate your account:</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>Cheers!</p>

project/templates/user/listPetitions.html
{% extends "_base.html" %}

{% block content %}

<h1>Current Petition:</h1>
<br>

{% endblock %}

project/templates/user/login.html
{% extends "_base.html" %}

{% block content %}

<style>

</style>


<h1 class="col-xs-6 col-xs-offset-4" style="text-align:;">Login</h1>
<br>

<form style="padding-left:;" class="col-xs-4 col-xs-offset-4 form-login" role="form" method="post" action="">
  {{ form.csrf_token }}

  <p>
    {{ form.email(placeholder="email") }}

    <span class="error">
      {% if form.email.errors %}
        {% for error in form.email.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>

  </p>

  <p>
  {{ form.password(placeholder="password") }}
    <span class="error">
      {% if form.password.errors %}
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>

  <button style="text-align: center;  color:white; font-weight:500; background-image: linear-gradient(#4365a8, #304978); border-radius:29px; font-size:19px; padding-top: 15px; padding-left: 73px;padding-right: 73px; padding-bottom: 15px; margin-top:15px;" class="btn btn-success" type="submit">Submit</button>
  <br><br><br>

  <p>Need to <a style="color:#3C5A99" href="/register">sign up</a>?</p>

</form>
</div>

{% endblock %}

project/templates/user/profile.html
{% extends "_base.html" %}

{% block content %}

<h1>Your Profile</h1>
<br>

{% if current_user.is_authenticated() %}
  <p>Email: {{current_user.email}}</p>
{% endif %}

<h2>Change Password</h2>
<br>

<form class="form-reset" role="form" method="post" action="">
  {{ form.csrf_token }}
  <p>
    {{ form.password(placeholder="password") }}
    <span class="error">
      {% if form.password.errors %}
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>

  <p>
  {{ form.confirm(placeholder="confirm") }}
    <span class="error">
      {% if form.confirm.errors %}
        {% for error in form.confirm.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>

  <button class="btn btn-success" type="submit">Update</button>
</form>

<h3><a href="{{ url_for('user.logout') }}">Logout</a></h3>


{% endblock %}

project/templates/user/register.html
{% extends "_base.html" %}

{% block content %}

<h1 class="col-xs-6 col-xs-offset-4">Sign up</h1>
<br>
<form class="col-xs-4 col-xs-offset-4 form-signin" role="form" method="post" action="">
  {{ form.csrf_token }}
  {{ form.email(placeholder="email") }}
    <span class="error">
      {% if form.email.errors %}
        {% for error in form.email.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.password(placeholder="password") }}
    <span class="error">
      {% if form.password.errors %}
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.confirm(placeholder="confirm") }}
    <span class="error">
      {% if form.confirm.errors %}
        {% for error in form.confirm.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button style="text-align: center;  color:white; font-weight:500; background-image: linear-gradient(#4365a8, #304978); border-radius:29px; font-size:19px; padding-top: 15px; padding-left: 73px;padding-right: 73px; padding-bottom: 15px; margin-top:15px;" class="btn btn-success" type="submit">Submit</button>
  <br><br>
  <p>Already have an account? <a style="color:#3C5A99" href="/login">Login</a>.</p>
</form>

{% endblock %}

project/templates/user/unconfirmed.html
{% extends "_base.html" %}

{% block content %}

<h1>Welcome!</h1>
<br>
<p>You have not confirmed your account. Please check your inbox (and your spam folder) - you should have received an email with a confirmation link.</p>
<p>Didn't get the email? <a href="{{ url_for('user.resend_confirmation') }}">Resend</a>.</p>

{% endblock %}